# Generated by Django 5.2.4 on 2025-07-10 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("phone", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("gdpr_consent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Subscriber",
                "verbose_name_plural": "Subscribers",
            },
        ),
        migrations.CreateModel(
            name="SubscriberSMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("gdpr_consent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "SMS Subscriber",
                "verbose_name_plural": "SMS Subscribers",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("gdpr_consent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
